site_name: Serialize
site_author: drake
site_description: Serialize document
copyright: Copyright &copy; 2018 - 2020 劉強東

repo_name: GitHub
repo_url: https://github.com/liangjingkanji/Serialize

extra_css:
  - css/extra.css

docs_dir: docs

theme:
  name: material
  custom_dir: docs/material

  palette:
    scheme: drake
    primary: white

  font: false

  language: zh

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed


nav:
  - 序列化: index.md
  - 页面传递参数: arguments.md
  - 更新日志: updates.md
  - 1.x文档: api/index.html
